---
apiVersion: v1
kind: Service
metadata:
  name: consignservice
  namespace: kube-ts-ns
  labels:
    app: consign-service
spec:
  type: ClusterIP
  ports:
    - port: 16111
      targetPort: 16111
  selector:
    app: consign-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consignservice
  namespace: kube-ts-ns
  labels:
    app: consign-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: consign-service
  template:
    metadata:
      labels:
        app: consign-service
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: consign-service
          image: $IMAGE_NAME
          ports:
            - containerPort: 16111
          volumeMounts:
            - mountPath: /var/log/mclient
              name: log-volume
          env:
            - name: MCLUSTER_IP
              value: "172.16.17.37"
            - name: MCLUSTER_PORT
              value: "30761"
      volumes:
        - name: log-volume
          hostPath:
            path: /data/test-dir/log

